name: Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}
