name: Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v2
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          ref: v${{ steps.semantic.outputs.new_release_version }}
